<?php

/**
 * Created by PhpStorm.
 * User: sannyasin
 * Date: 1/20/2016
 * Time: 9:30 AM
 */
class Handbook extends _BasePost
{
    public $uploadImageFolder = 'upload/cms'; //remember remove ending slash
    public $defineImageSize = array(
        'featured_image' => array(array('alias' => 'thumb1', 'size' => '320x310')),
    );
    public $pageType = 'handbook';
    public $categoryId;

    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public function rules()
    {
        $retRules = parent::rules();
        $retRules[] = array('short_content,content,title', 'safe');
        return $retRules;
    }

    public function defaultScope()
    {
        return array(
            'condition'=>"post_type='" . $this->pageType . "'",
        );
    }

    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        $return =  array(
        );
        return $return;
    }

    public function getSlugById($id)
    {
        return Handbook::model()->findByPk((int)$id);
    }

    protected function beforeSave()
    {
        $this->post_type = $this->pageType;
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

    public function getAllGrid() {
        $criteria=new CDbCriteria;
        $criteria->compare('status', STATUS_ACTIVE);
        $criteria->order = 'modified_date DESC, created_date DESC';
        return new CActiveDataProvider('Handbook', array(
            'criteria'=>$criteria,
            'pagination' => array(
                'pageSize' => 6,
            ),
        ));
    }

    public function getLatest() {
        $criteria=new CDbCriteria;
        $criteria->compare('status', STATUS_ACTIVE);
        $criteria->order = 'modified_date DESC, created_date DESC';
        $criteria->limit = 5;
        return self::model()->findAll($criteria);
    }

    public function getRelate($id) {
        $criteria=new CDbCriteria;
        $criteria->addCondition('id != '.$id);
        $criteria->compare('status', STATUS_ACTIVE);
        $criteria->order = 'modified_date DESC, created_date DESC';
        $criteria->limit = 6;
        return self::model()->findAll($criteria);
    }

    public function nextOrderNumber()
    {
        return Handbook::model()->count() + 1;
    }

    /**
     * @Author Haidt <haidt3004@gmail.com>
     * @copyright 2015 Verz Design
     * @return string
     * @Todo: render featured image
     */
    public function getFeaturedImage($size = 'thumbs') {
        if (!empty($this->featured_image)) {
            return CHtml::image(ImageHelper::getImageUrl($this, 'featured_image', $size), $this->featured_image);
        }
        return '';
    }

    /**
     * @Author Haidt <haidt3004@gmail.com>
     * @copyright 2015 Verz Design
     * @return string
     * @Todo: get title of Handbook
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * @Author Haidt <haidt3004@gmail.com>
     * @copyright 2015 Verz Design
     * @return string
     * @Todo: get description of Handbook
     */
    public function getDescription() {
        return $this->short_content;
    }

    /**
     * @Author Haidt <haidt3004@gmail.com>
     * @copyright 2015 Verz Design
     * @return string
     * @Todo: get content of Handbook
     */
    public function getContent() {
        return $this->content;
    }

}
