<?php

/**
 * Created by PhpStorm.
 * User: sannyasin
 * Date: 1/20/2016
 * Time: 9:30 AM
 */
class OrgChart extends _BasePostNoMulti
{
    public $uploadImageFolder = 'upload/cms'; //remember remove ending slash
    public $defineImageSize = array(
        'featured_image' => array(array('alias' => 'thumb1', 'size' => '320x310')),
    );
    public $pageType = 'org-chart';
    public $categoryId;

    //multi language
    public $modelTranslate ='OrgChartsTranslate';
    public $short_content;
    public $content;
    public $title;
    //multi language


    public function attributeLabels()
    {
        $attr = parent::attributeLabels();
        $attr['short_content'] = Yii::t('translation', 'Link');
        return $attr;
    }


    public function tableName()
    {
        return '{{_org_charts}}';
    }

    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public function rules()
    {
        $retRules = parent::rules();
        $retRules[] = array('short_content,content,title', 'safe');
        return $retRules;
    }

    public function defaultScope()
    {
        return array(
            'condition'=>"post_type='" . $this->pageType . "'",
        );
    }

    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        $return =  array(
            'translate' => array(self::HAS_MANY, $this->modelTranslate, 'translate_id','limit' => 1,'on'=>"translate.language='".Yii::app()->language."'"),   
        );
        return $return;
    }

    public function getSlugById($id)
    {
        return OrgChart::model()->findByPk((int)$id);
    }

    protected function beforeSave()
    {
        $this->post_type = $this->pageType;
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

    public function getAllGrid() {
        $criteria=new CDbCriteria;
        $criteria->compare('status', STATUS_ACTIVE);
        // gioi han search theo tung website
        $criteria->compare('role_website_id', ROLE_WEBSITE_ID, true);
        $criteria->order = 'modified_date DESC, created_date DESC';
        return new CActiveDataProvider('OrgChart', array(
            'criteria'=>$criteria,
            'pagination' => array(
                'pageSize' => 6,
            ),
        ));
    }

    public function getLatest() {
        $criteria=new CDbCriteria;
        $criteria->compare('status', STATUS_ACTIVE);
        // gioi han search theo tung website
        $criteria->compare('role_website_id', ROLE_WEBSITE_ID, true);
        $criteria->order = 'modified_date DESC, created_date DESC';
        $criteria->limit = 5;
        return self::model()->findAll($criteria);
    }

    public function getRelate($id) {
        $criteria=new CDbCriteria;
        $criteria->addCondition('id != '.$id);
        $criteria->compare('status', STATUS_ACTIVE);
        // gioi han search theo tung website
        $criteria->compare('role_website_id', ROLE_WEBSITE_ID, true);
        $criteria->order = 'modified_date DESC, created_date DESC';
        $criteria->limit = 6;
        return self::model()->findAll($criteria);
    }

    public function nextOrderNumber()
    {
        return OrgChart::model()->count() + 1;
    }

    /**
     * @Author Haidt <haidt3004@gmail.com>
     * @copyright 2015 Verz Design
     * @return string
     * @Todo: render featured image
     */
    public function getFeaturedImage($size = 'thumbs') {
        if (!empty($this->featured_image)) {
            return CHtml::image(ImageHelper::getImageUrl($this, 'featured_image', $size), $this->featured_image);
        }
        return '';
    }

    /**
     * @Author Haidt <haidt3004@gmail.com>
     * @copyright 2015 Verz Design
     * @return string
     * @Todo: get title of OrgChart
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * @Author Haidt <haidt3004@gmail.com>
     * @copyright 2015 Verz Design
     * @return string
     * @Todo: get description of OrgChart
     */
    public function getDescription() {
        return $this->short_content;
    }

    /**
     * @Author Haidt <haidt3004@gmail.com>
     * @copyright 2015 Verz Design
     * @return string
     * @Todo: get content of OrgChart
     */
    public function getContent() {
        return $this->content;
    }

    
    public function showTile(){
         $this->getDataTranslate();
         return $this->title;
    }
    

}
